language: node_js
node_js:
  - "11"

before_script:
  - npm run setup
  - npm run build

script:
  - echo "skipping tests"


after_script:
  - echo "skipping coverage"

after_success:
  - npm pack


deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: lib.tgz
    skip_cleanup: true
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: ryderbrooks@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true

